### ISSUE TITLE
instructions?

### ISSUE THREAD

**Issue by dchmelik** [teleshoes/chatpop-pidgin#1]
Can you write compiling instructions?

**Comment by teleshoes** [comment]
gnu/linux instructions are already in `./install.sh`
```
~/Code/chatpop-pidgin$ cat install.sh 
#!/bin/sh
gcc chatpop.c -o chatpop.so \
  -fPIC -shared `pkg-config pidgin --cflags --libs glib-2.0` \
  -Wall -Werror-implicit-function-declaration \
  && sudo mkdir -p /usr/lib/purple-2/ \
  && sudo cp chatpop.so /usr/lib/purple-2/
```


that gcc line looks like this for me:
`gcc chatpop.c -o chatpop.so -fPIC -shared -I/usr/include/pidgin -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/webp -I/usr/include/atk-1.0 -pthread -I/usr/include/libpurple -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lharfbuzz -lfontconfig -lfreetype -lpurple -lglib-2.0 -Wall -Werror-implicit-function-declaration`

happy coding!
